-- DROP TABLE IF EXISTS account;

-- SELECT *
-- FROM account;

-- CREATE TABLE IF NOT EXISTS public.account
-- (
--     account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     account_firstname character varying NOT NULL,
--     account_lastname character varying NOT NULL,
--     account_email character varying NOT NULL,
--     account_password character varying NOT NULL,
--     account_type account_type NOT NULL DEFAULT 'Client'::account_type,
--     CONSTRAINT account_pkey PRIMARY KEY (account_id)
-- );

SELECT *
FROM account;

INSERT INTO account
(account_firstname, account_lastname, account_email, account_password)
VALUES ( 'Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n');

SELECT *
FROM account;

UPDATE account
SET account_type = 'Admin'
WHERE account_id = 1;

DELETE FROM account
WHERE account_id = 1;

-- REPLACE(column, from_text, to_text);

SELECT *
FROM inventory;

-- UPDATE inventory
-- SET inv_description = REPLACE(inv_description, 'a huge interior', 'small interiors')
-- WHERE inv_make = 'GM' AND inv_model = 'Hummer';

UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

SELECT inv.inv_make AS make, inv.inv_model AS model, clas.classification_name AS classification
FROM inventory inv INNER JOIN classification clas
ON inv.classification_id = clas.classification_id
WHERE clas.classification_name = 'Sport';


-- UPDATE inventory
-- SET inv_image = REPLACE(inv_image, '/images/vehicles', '/images'),
-- 	inv_thumbnail = REPLACE(inv_thumbnail, '/images/vehicles', '/images');

SELECT *
FROM inventory;

UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images', '/images/vehicles'),
	inv_thumbnail = REPLACE(inv_thumbnail, '/images', '/images/vehicles');
	
SELECT *
FROM inventory;

